version: "3"
services:
  www:
    volumes:
      - ./server-data:/opt/app/server-data
    ports:
      - "80:80"
    build:
      context: .
    image: kimbtechnologies/wbo:latest
    restart: on-failure
    environment: 
      - SITE_NAME=My wbo
      - ABOUT_LINK=http://example.com
      - ABOUT_TITLE=Imprint and Privacy
      - SHOW_ANONYMOUS=false
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 60s
