version: '3'
services:
  www:
    volumes:
      - /opt/app/server-data:/opt/app/server-data
    ports:
      - '80:80'
    build:
      context: .
    restart: on-failure
    environment: 
      - SITE_NAME=My wbo
      - ABOUT_LINK=http://example.com
      - ABOUT_TITLE=Imprint and Privacy
      - SHOW_ANONYMOUS=false
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 60s

